const perform = async (z, bundle) => {
  const response = await z.request({
    url: `${bundle.authData.server_url}/api/zapier/actions/schedule-calendar-time`,
    method: 'POST',
    headers: {
      Authorization: `Bearer ${bundle.authData.api_key}`,
      'Content-Type': 'application/json',
    },
    body: {
      eventType: bundle.inputData.eventType,
      date: bundle.inputData.date,
      startTime: bundle.inputData.startTime,
      endTime: bundle.inputData.endTime,
      title: bundle.inputData.title,
      notes: bundle.inputData.notes,
      status: bundle.inputData.status,
      customerName: bundle.inputData.customerName,
      customerEmail: bundle.inputData.customerEmail,
      customerPhone: bundle.inputData.customerPhone,
      customerAddress: bundle.inputData.customerAddress,
    },
  });

  return response.data;
};

module.exports = {
  key: 'schedule_calendar_time',
  noun: 'Calendar Event',
  display: {
    label: 'Schedule Calendar Time',
    description: 'Creates a booked appointment or blocks a time range on your calendar.',
  },
  operation: {
    perform,
    inputFields: [
      {
        key: 'eventType',
        label: 'Event Type',
        type: 'string',
        required: true,
        choices: {
          booking: 'Booking',
          blocked: 'Blocked Time',
        },
        helpText: 'Choose whether this action should create a booked appointment or a blocked time entry.',
      },
      {
        key: 'date',
        label: 'Date',
        type: 'string',
        required: true,
        helpText: 'Date for the calendar entry in YYYY-MM-DD format.',
      },
      {
        key: 'startTime',
        label: 'Start Time',
        type: 'string',
        required: true,
        helpText: 'Start time in 24-hour HH:MM format.',
      },
      {
        key: 'endTime',
        label: 'End Time',
        type: 'string',
        required: true,
        helpText: 'End time in 24-hour HH:MM format.',
      },
      {
        key: 'title',
        label: 'Title',
        type: 'string',
        required: false,
        helpText: 'Optional calendar title. Defaults to "Customer Appointment" for bookings or "Blocked Time" for blocked entries.',
      },
      {
        key: 'notes',
        label: 'Notes',
        type: 'text',
        required: false,
        helpText: 'Optional notes or description for the calendar entry.',
      },
      {
        key: 'status',
        label: 'Booking Status',
        type: 'string',
        required: false,
        choices: {
          confirmed: 'Confirmed',
          tentative: 'Tentative',
        },
        helpText: 'Used for booking events only. Defaults to confirmed.',
      },
      {
        key: 'customerName',
        label: 'Customer Name',
        type: 'string',
        required: false,
        helpText: 'Optional customer name for booking events.',
      },
      {
        key: 'customerEmail',
        label: 'Customer Email',
        type: 'string',
        required: false,
        helpText: 'Optional customer email for booking events.',
      },
      {
        key: 'customerPhone',
        label: 'Customer Phone',
        type: 'string',
        required: false,
        helpText: 'Optional customer phone for booking events.',
      },
      {
        key: 'customerAddress',
        label: 'Customer Address',
        type: 'string',
        required: false,
        helpText: 'Optional service address for booking events.',
      },
    ],
    sample: {
      id: 'booking_42',
      type: 'booking',
      date: '2026-04-06',
      startTime: '09:00',
      endTime: '11:00',
      title: 'Roof Cleaning - Jane Doe',
      status: 'confirmed',
      calendarEventId: 42,
      availabilitySlotId: 18,
      startsAt: '2026-04-06T09:00:00.000Z',
      endsAt: '2026-04-06T11:00:00.000Z',
    },
    outputFields: [
      { key: 'id', label: 'Result ID', type: 'string' },
      { key: 'type', label: 'Event Type', type: 'string' },
      { key: 'date', label: 'Date', type: 'string' },
      { key: 'startTime', label: 'Start Time', type: 'string' },
      { key: 'endTime', label: 'End Time', type: 'string' },
      { key: 'title', label: 'Title', type: 'string' },
      { key: 'notes', label: 'Notes', type: 'string' },
      { key: 'status', label: 'Status', type: 'string' },
      { key: 'calendarEventId', label: 'Calendar Event ID', type: 'integer' },
      { key: 'availabilitySlotId', label: 'Availability Slot ID', type: 'integer' },
      { key: 'startsAt', label: 'Starts At', type: 'datetime' },
      { key: 'endsAt', label: 'Ends At', type: 'datetime' },
      { key: 'customerName', label: 'Customer Name', type: 'string' },
      { key: 'customerEmail', label: 'Customer Email', type: 'string' },
      { key: 'customerPhone', label: 'Customer Phone', type: 'string' },
      { key: 'customerAddress', label: 'Customer Address', type: 'string' },
    ],
  },
};
